// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartWallet.Infrastructure;

#nullable disable

namespace SmartWallet.Infrastructure.Migrations
{
    [DbContext(typeof(SmartWalletDbContext))]
    [Migration("20251109204115_seed de datos")]
    partial class seeddedatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartWallet.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrencyCode")
                        .HasColumnType("int");

                    b.Property<Guid?>("DestinationWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DestinationWalletId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SmartWallet.Domain.Entities.TransactionLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CurrencyCode")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WalletId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WalletId2")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.HasIndex("WalletId1");

                    b.HasIndex("WalletId2");

                    b.ToTable("TransactionLedgers");
                });

            modelBuilder.Entity("SmartWallet.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9f692ac-c922-446c-95dd-d4ad84ced22e"),
                            Active = true,
                            CreatedAt = new DateTime(2025, 11, 9, 20, 41, 15, 337, DateTimeKind.Utc).AddTicks(9416),
                            Email = "albus@mail.com",
                            Name = "Albus Dumbledore",
                            PasswordHash = "1234",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("e89356b7-4ae1-4cb3-a37a-b28b7c8243b0"),
                            Active = true,
                            CreatedAt = new DateTime(2025, 11, 9, 20, 41, 15, 337, DateTimeKind.Utc).AddTicks(9421),
                            Email = "admin@mail.com",
                            Name = "Admin Admin",
                            PasswordHash = "1234",
                            Role = 2
                        });
                });

            modelBuilder.Entity("SmartWallet.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("SmartWallet.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("SmartWallet.Domain.Entities.Wallet", "DestinationWallet")
                        .WithMany("ReceivedTransfers")
                        .HasForeignKey("DestinationWalletId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartWallet.Domain.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationWallet");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("SmartWallet.Domain.Entities.TransactionLedger", b =>
                {
                    b.HasOne("SmartWallet.Domain.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartWallet.Domain.Entities.Wallet", null)
                        .WithMany("DestinationLedgers")
                        .HasForeignKey("WalletId1");

                    b.HasOne("SmartWallet.Domain.Entities.Wallet", null)
                        .WithMany("SourceLedgers")
                        .HasForeignKey("WalletId2");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("SmartWallet.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("SmartWallet.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartWallet.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("DestinationLedgers");

                    b.Navigation("ReceivedTransfers");

                    b.Navigation("SourceLedgers");
                });
#pragma warning restore 612, 618
        }
    }
}
